### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by zenimar** [sup3rgiu/PoliDown#20]
at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at downloadVideo (D:\stream-test\PoliDown-master\polidown.js:338:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I really appreciate your job! 
When I download multiple videos, it randomly happens this error.
it's not related to a particular video, because rerunning the program on the same video solve the problem. I normally put 5 videos link in the same command.
thank you

**Comment by polifriend** [comment]
sadly, this script always occurs when I try to download everything.

...
Reusing password saved in system's keychain!

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
Filling in Servizi Online login form...
(node:8744) UnhandledPromiseRejectionWarning: TimeoutError: waiting for target f
ailed: timeout 90000ms exceeded
    at Function.waitWithTimeout (C:\projects\PoliDown\node_modules\puppeteer\lib
\helper.js:228:26)
    at Browser.waitForTarget (C:\projects\PoliDown\node_modules\puppeteer\lib\Br
owser.js:214:27)
    at Browser.<anonymous> (C:\projects\PoliDown\node_modules\puppeteer\lib\help
er.js:112:23)
    at downloadVideo (C:\projects\PoliDown\polidown.js:164:18)
(node:8744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:8744) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by talipturkmen** [comment]
Hello everyone,

Isn't there any solution for this problem?  It gives this error when I try to download multiple videos.

Thank you

**Comment by talipturkmen** [comment]
I think I've found the reason of the problem. It returns this error when there is no extension of the file of which you have links in it. If you add the extension as .txt it resolves the problem.

**Comment by IlBoriss** [comment]
I have this problem every time i try to download a video. I tried different ways to give the URL, but never worked

`audio_tmp.m3u8: Invalid data found when processing input
(node:7204) UnhandledPromiseRejectionWarning: Error: Command failed: ffmpeg -protocol_whitelist file,http,https,tcp,tls,crypto,data -allowed_extensions ALL -i audio_tmp.m3u8 -protocol_whitelist file,http,https,tcp,tls,crypto,data -allowed_extensions ALL -i video_tmp.m3u8 -async 1 -c copy -bsf:a aac_adtstoasc -n "..\..\videos\Lesson 12_05_2020 - TURRI STEFANO ETTORE ROMANO  089723-POLYMER TECHNOLOGY AND SUSTAINABILITY (712958).mp4"
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at downloadVideo (C:\Video Polimi\PoliDown\polidown.js:382:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by sansyo-k** [comment]
Hello, everyone.
I'm using translation.
I'm having the same problem and I can't download it.
I can't even download a single video.
I've heard that changing the extension as .txt will solve the problem, but I don't how do I do that
could anyone tell me how to do this ?
Thank you to the creator.

PS

Are you talking about the extension of a file that contains multiple links?
If so, it is probably a different problem for me.
